### ISSUE TITLE
How do I download the complete dataset?

### ISSUE THREAD

**Issue by Kirang96** [isl-org/spear#162]
The title.
I was unable to find the complete dataset with all the scenes. I could only get one of the scenes from the releases page. Please guide how to download it.

**Comment by mikeroberts3000** [comment]
Hi @Kirang96, great question. We're planning on releasing more scenes in the near future. In the meantime, we wanted to release our test scene as soon as it was ready, for people that want to begin experimenting with our platform immediately.
