### ISSUE TITLE
Suggestion for an additional tutorial

### ISSUE THREAD

**Issue by monajalal** [isl-org/spear#187]
Hi Mike, 

Thanks a lot for your responses. 

I thought this might be an interesting tutorial that could be added in either as part of generate_images.py or standalone as generate_object_pose.

Input: a list of objects that user decides to be annotated with 2D and 3D bounding boxes
Output: a JSON file for each image showing the 2D and 3D BBox coordinates (eg. similar to NDDS format)

**Comment by mikeroberts3000** [comment]
This is a great idea. We'd love your help with this. There are some code modifications that would be required, which I posted in your previous question.
