### ISSUE TITLE
How to download the 300 virtual indoor scenes mentioned in README.md?

### ISSUE THREAD

**Issue by AgentEXPL** [isl-org/spear#237]
As written in readme.md, there are 300 unique virtual indoor environments with 2,566 unique rooms and 17,234 unique objects, how to download these scenes?

**Comment by mikeroberts3000** [comment]
Hi AgentEXPL, great question! We're in the process of updating our scenes to use the latest photorealistic rendering features in Unreal Engine 5. We're not quite ready to ship our other scenes yet, but we consider this a high priority and we're actively working on it. Stay tuned! 😀
