### ISSUE TITLE
Programmatically inserting custom objects?

### ISSUE THREAD

**Issue by AmineElhafsi** [isl-org/spear#256]
Hello,

Is it possible to insert custom models into this simulation via the python interface?

Thanks

**Comment by mikeroberts3000** [comment]
This is not currently possible via the Python interface, but it would be possible with a bit of effort. It would involve getting your custom objects imported as `uasset` files into our Unreal project (i.e., `SpearSim.uproject`), writing a new C++ function to spawn a user-specified asset at a user-specified location, and then exposing the C++ function to our Python interface. If you're interested in giving this a try, the best place to start would be going through our Getting Started and Building SpearSim tutorials. Once you're finished these tutorials, post here and we can guide you from there.
