### ISSUE TITLE
Small typo in SpCore/StableNameComponent.cpp and SpCore/UserInputComponent.cpp

### ISSUE THREAD

**Issue by quentin-leboutet** [isl-org/spear#272]
There are a couple of `#pragma once` in [SpCore/StableNameComponent.cpp](https://github.com/isl-org/spear/blob/d1382da08ac90dc06257a9b5ff32a6b2273bc470/cpp/unreal_plugins/SpCore/Source/SpCore/StableNameComponent.cpp#L5) and [SpCore/UserInputComponent.cpp](https://github.com/isl-org/spear/blob/d1382da08ac90dc06257a9b5ff32a6b2273bc470/cpp/unreal_plugins/SpCore/Source/SpCore/UserInputComponent.cpp#L5) preventing build. Removing them fixes the build.

**Comment by mikeroberts3000** [comment]
Good catch, thank you for submitting. This, and the previous issue you reported, is fixed in `main`.
