### ISSUE TITLE
Independent Mujoco Simulation

### ISSUE THREAD

**Issue by omarrayyann** [isl-org/spear#295]
Is there a way to run the MuJoCo simulation without Unreal engine?

**Comment by mikeroberts3000** [comment]
Hi! Good question. Yes. The output of our export pipeline is an MJCF file, which you can run in MuJoCo however you prefer. And, of course, you can comment out all the parts of our example code that touch the `spear` Python API. If you do this, you will be left with a short (i.e., roughly 20 lines of code) standalone script that launches a MuJoCo window and loads an MJCF file.

**Comment by omarrayyann** [comment]
Yes that would be great. I am trying to use MuJoCo since my laptop can't handle Unreal Engine.
